#!/bin/python3

import sys
import os

def run_example(filename):
	exename = f"{filename}-out"
	os.system(f"gcc -o {exename} examples/{filename}.c src/potatui.c -lncursesw")
	os.system(f"./{exename}")
	os.system(f"rm ./{exename}")

def build_lib():
	print("building...")

match sys.argv[1]:
	case "run":
		run_example(sys.argv[2])
	case "build":
		build_lib()
