#!/bin/python3

import sys
import os

def run_example(filename):
	exename = f"{filename}-out"
	os.system(f"gcc -o {exename} examples/{filename}.c src/manatui.c -lncursesw")
	os.system(f"./{exename}")
	os.system(f"rm ./{exename}")

run_example(sys.argv[1])
